apiVersion: v2
name: opsdiag-app-mcp-server
description: OpsDiag app MCP server API
type: application
version: 0.1.1
appVersion: "2026-06-25.22-42-36.b965a0"
home: https://opsdiag.ai
sources:
  - https://github.com/presemantic/opsdiag-app-mcp-server-api
dependencies:
  - name: common
    repository: https://opsolving.github.io/charts/
    version: 2.x.x
