apiVersion: v2
name: opsdiag-app-mcp-proxy
description: OpsDiag app MCP proxy API
type: application
version: 0.1.1
appVersion: "2026-06-25.22-42-36.a3b694"
home: https://opsdiag.ai
sources:
  - https://github.com/presemantic/opsdiag-app-mcp-proxy-api
dependencies:
  - name: common
    repository: https://opsolving.github.io/charts/
    version: 2.x.x
