apiVersion: v2
name: opsolving-app
description: Complete Opsolving application stack
type: application
version: 1.0.25
appVersion: "2026-08-29.23-46-38.1f3afea"
dependencies:
  - name: common
    repository: https://opsolving.github.io/charts/
    version: 2.x.x
  - name: apisix
    repository: https://charts.apiseven.com
    version: 2.16.0
