apiVersion: v2
name: opsolving-app
description: Complete Opsolving application stack
type: application
version: 1.0.27
appVersion: "2026-08-30.02-12-01.3149d2c"
dependencies:
  - name: common
    repository: https://opsolving.github.io/charts/
    version: 2.x.x
  - name: apisix
    repository: https://charts.apiseven.com
    version: 2.16.0
