apiVersion: v2
name: opsdiag-app-agent
description: OpsDiag app agent API
type: application
version: 0.1.1
appVersion: "2026-06-25.22-42-36.1a6244"
home: https://opsdiag.ai
sources:
  - https://github.com/presemantic/opsdiag-app-agent-api
dependencies:
  - name: common
    repository: https://opsolving.github.io/charts/
    version: 2.x.x
