apiVersion: v2
name: opsdiag-app-sched
description: OpsDiag app scheduler
type: application
version: 0.1.1
appVersion: "2026-06-25.22-42-36.4df732"
home: https://opsdiag.ai
sources:
  - https://github.com/presemantic/opsdiag-app-sched
dependencies:
  - name: common
    repository: https://opsolving.github.io/charts/
    version: 2.x.x
