## @section Global parameters
global:
  imageRegistry: ""
  imagePullSecrets: []

## @section Common parameters
nameOverride: ""
fullnameOverride: ""
namespaceOverride: ""
commonLabels: {}
commonAnnotations: {}
component: sched
containerName: sched

## @section Image parameters
image:
  registry: europe-west1-docker.pkg.dev
  repository: prod-common-cicd/opsdiag-docker-pub/opsdiag-app-sched
  tag: "2026-06-25.22-42-36.4df732"
  digest: ""
  pullPolicy: IfNotPresent
  pullSecrets: []

## @section Runtime config file
config: {}

## @section Deployment parameters
replicaCount: 1
revisionHistoryLimit: 10
updateStrategy:
  type: RollingUpdate
command: []
args: []
extraEnvVars: []
extraEnvVarsCM: ""
extraEnvVarsSecret: ""
extraVolumes: []
extraVolumeMounts: []
extraDeploy: []

## @section Service account parameters
serviceAccount:
  create: true
  name: ""
  annotations: {}
  automountServiceAccountToken: false

## @section Pod security parameters
podSecurityContext:
  enabled: true
  seccompProfile:
    type: RuntimeDefault
containerSecurityContext:
  enabled: true
  runAsNonRoot: true
  readOnlyRootFilesystem: true
  allowPrivilegeEscalation: false
  capabilities:
    drop:
      - ALL

## @section Service parameters
containerPorts:
  http: 8000
service:
  type: ClusterIP
  annotations: {}
  ports:
    http: 8000
  clusterIP: ""

## @section Resource parameters
resourcesPreset: nano
resources: {}

## @section Healthcheck parameters
livenessProbe:
  enabled: true
  spec:
    httpGet:
      path: /api/health
      port: http
readinessProbe:
  enabled: true
  spec:
    httpGet:
      path: /api/health
      port: http
startupProbe:
  enabled: false
  spec: {}

## @section Scheduling parameters
podLabels: {}
podAnnotations: {}
podAffinityPreset: ""
podAntiAffinityPreset: soft
nodeAffinityPreset:
  type: ""
  key: ""
  values: []
affinity: {}
nodeSelector: {}
tolerations: []
topologySpreadConstraints: []
priorityClassName: ""
schedulerName: ""
terminationGracePeriodSeconds: 30
