apiVersion: v2
name: opsdiag-connector
description: OpsDiag customer-side gateway connector
type: application
version: 0.1.1
appVersion: "2026-06-22.00-19-02.7b61a8"
home: https://opsdiag.ai
sources:
  - https://github.com/presemantic/opsdiag-gateway-connector
dependencies:
  - name: common
    repository: https://opsolving.github.io/charts/
    version: 2.x.x
